# Generated by Django 5.2.17 on 2026-09-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('INTRUSION', 'Restricted Zone Intrusion'), ('NIGHT_MOVEMENT', 'Night Movement Detected'), ('ANPR_MATCH', 'Watchlist ANPR Match'), ('LOITERING', 'Perimeter Loitering'), ('UNAUTHORIZED_VEHICLE', 'Unauthorized Vehicle Entry'), ('PERIMETER_CROSSING', 'Virtual Fence Crossing')], default='INTRUSION', max_length=50)),
                ('object_type', models.CharField(choices=[('Person', 'Person / Pedestrian'), ('Vehicle', 'Motor Vehicle'), ('Animal', 'Animal / Wildlife'), ('Unknown', 'Unidentified Object')], default='Person', max_length=50)),
                ('threat_score', models.IntegerField(default=70)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('evidence_image', models.CharField(blank=True, max_length=300)),
                ('details', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.94)),
                ('coordinates', models.CharField(default='32.7266 N, 74.8570 E', max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
