# Generated by Django 5.2.17 on 2026-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('INTRUSION', 'Restricted Zone Intrusion'), ('NIGHT_MOVEMENT', 'Night Movement Detected'), ('FRS_MATCH', 'Biometric FRS Watchlist Match'), ('ANPR_MATCH', 'Watchlist ANPR Match'), ('LOITERING', 'Perimeter Loitering & Reconnaissance'), ('CRAWLING_CONCEALMENT', 'Prone / Low-Crawl Infiltration Movement'), ('SUSPICIOUS_PACKAGE_DROP', 'Unattended Contraband / Object Drop'), ('CROWD_SURGE', 'Abnormal Crowd Clustering / Surge'), ('UNAUTHORIZED_VEHICLE', 'Unauthorized Vehicle Entry'), ('PERIMETER_CROSSING', 'Virtual Fence Crossing')], default='INTRUSION', max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='object_type',
            field=models.CharField(choices=[('Person', 'Person / Pedestrian'), ('Vehicle', 'Motor Vehicle'), ('Package', 'Unattended Baggage / Contraband'), ('Animal', 'Animal / Wildlife'), ('Unknown', 'Unidentified Object')], default='Person', max_length=50),
        ),
    ]
