# Generated by Django 5.2.17 on 2026-09-01 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('threat_score', models.IntegerField(default=75, help_text='Calculated risk value 0-100')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Unresolved'), ('ACKNOWLEDGED', 'Acknowledged by Officer'), ('RESOLVED', 'Resolved & Cleared')], default='ACTIVE', max_length=20)),
                ('detected_object', models.CharField(default='Person', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('evidence_image', models.CharField(blank=True, help_text='Path or SVG visual representation', max_length=300)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cameras.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
