# Generated by Django 5.2.17 on 2026-09-01 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('OFFICER', 'Security Officer')], default='OFFICER', max_length=20)),
                ('badge_number', models.CharField(blank=True, default='IND-BSF-042', max_length=50)),
                ('sector_assignment', models.CharField(default='Western Sector Command', max_length=100)),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
