# Generated by Django 5.2.17 on 2026-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(default='Car', max_length=50)),
                ('description', models.TextField(help_text='Reason for flagging (Sample/Demo data)')),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical Priority (Immediate Detain)'), ('HIGH', 'High Risk (Flag & Monitor)'), ('MEDIUM', 'Medium Risk (Secondary Inspection)'), ('LOW', 'Low Risk (Informational)')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active Flag'), ('Investigating', 'Under Investigation'), ('Resolved', 'Cleared / Inactive')], default='Active', max_length=20)),
                ('reported_sector', models.CharField(default='Sector 01 - Western Frontier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-risk_level', '-created_at'],
            },
        ),
    ]
