# Generated by Django 5.2.17 on 2026-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(help_text='e.g. FRS-IND-042', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, help_text='Known aliases or callsigns', max_length=150)),
                ('category', models.CharField(choices=[('INFILTRATOR', 'Cross-Border Infiltrator / Terrorist'), ('SMUGGLER', 'Contraband / Narcotics Smuggler'), ('SUSPECT', 'Wanted Criminal / Fugitive'), ('POW_DETAINEE', 'Escapee / Detainee of Interest'), ('PERSON_OF_INTEREST', 'General Person of Interest')], default='INFILTRATOR', max_length=50)),
                ('threat_level', models.CharField(choices=[('CRITICAL', 'Critical (Immediate Intercept)'), ('HIGH', 'High Risk (Armed / Infiltrator)'), ('MEDIUM', 'Medium Risk (Suspected Smuggler)'), ('LOW', 'Low Risk (Person of Interest)')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active Wanted Notice'), ('Apprehended', 'Apprehended / Detained'), ('Investigating', 'Under Investigation'), ('Cleared', 'Cleared / Inactive')], default='Active', max_length=20)),
                ('facial_embedding_id', models.CharField(blank=True, help_text='AI Feature Vector / Embedding Hash', max_length=100)),
                ('last_seen_sector', models.CharField(default='Sector 01 - Forward Outpost Alpha', max_length=150)),
                ('reason_for_flagging', models.TextField(help_text='Intelligence dossier notes / reason for biometric watchlist entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-threat_level', '-created_at'],
            },
        ),
    ]
