# Generated by Django 5.2.17 on 2026-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(help_text='e.g. BOP-01, GATE-01', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='e.g. Sector 01 - Forward Post Alpha', max_length=200)),
                ('feed_type', models.CharField(choices=[('LIVE', 'LIVE — WEBCAM'), ('SIMULATION', 'SIMULATION — VIDEO')], default='SIMULATION', max_length=20)),
                ('source_type', models.CharField(choices=[('WEBCAM', 'Local Laptop Webcam / USB'), ('VIDEO_FILE', 'Simulated Border Video Asset'), ('RTSP_STREAM', 'RTSP / Network CCTV Feed')], default='VIDEO_FILE', max_length=20)),
                ('source_url', models.CharField(blank=True, help_text='RTSP URL, file path, or device index 0', max_length=500)),
                ('status', models.CharField(choices=[('ONLINE', 'Online / Operational'), ('STANDBY', 'Standby'), ('OFFLINE', 'Offline / Connection Lost')], default='ONLINE', max_length=20)),
                ('people_count', models.IntegerField(default=0)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('is_ai_active', models.BooleanField(default=True)),
                ('threat_level', models.CharField(choices=[('NORMAL', 'Normal'), ('ELEVATED', 'Elevated'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('enable_human_detection', models.BooleanField(default=True, verbose_name='Human Detection')),
                ('enable_vehicle_detection', models.BooleanField(default=True, verbose_name='Vehicle Classification')),
                ('enable_anpr', models.BooleanField(default=False, verbose_name='ANPR / OCR')),
                ('enable_intrusion_detection', models.BooleanField(default=True, verbose_name='Virtual Fence Intrusion')),
                ('enable_night_detection', models.BooleanField(default=True, verbose_name='Night-Time Vision / Movement')),
                ('latitude', models.FloatField(default=32.7266)),
                ('longitude', models.FloatField(default=74.857)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['camera_id'],
            },
        ),
    ]
