# Generated by Django 5.2.17 on 2026-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='enable_behavioral_analytics',
            field=models.BooleanField(default=True, verbose_name='Behavioral / Activity Analytics'),
        ),
        migrations.AddField(
            model_name='camera',
            name='enable_frs',
            field=models.BooleanField(default=True, verbose_name='Facial Recognition (FRS)'),
        ),
    ]
