# Generated by Django 5.2.17 on 2026-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_start_time', models.CharField(default='22:00', max_length=10)),
                ('night_end_time', models.CharField(default='05:00', max_length=10)),
                ('weight_person_detection', models.IntegerField(default=20)),
                ('weight_night_movement', models.IntegerField(default=15)),
                ('weight_restricted_zone', models.IntegerField(default=30)),
                ('weight_loitering', models.IntegerField(default=10)),
                ('weight_watchlist_vehicle', models.IntegerField(default=40)),
                ('auto_refresh_rate', models.IntegerField(default=5, help_text='Stream sync interval in seconds')),
                ('audio_alerts', models.BooleanField(default=True)),
                ('high_threat_threshold', models.IntegerField(default=75)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
