# Generated by Django 5.2.17 on 2026-09-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANPRDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=30)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Sedan / Hatchback'), ('SUV', 'SUV / 4x4 Off-road'), ('Truck', 'Commercial Heavy Truck'), ('Motorcycle', 'Motorcycle / Two-Wheeler'), ('Bus', 'Transport Bus'), ('Van', 'Cargo / Delivery Van')], default='Car', max_length=50)),
                ('confidence', models.FloatField(default=0.95, help_text='OCR Confidence Score (0.00 to 1.00)')),
                ('is_watchlist_match', models.BooleanField(default=False)),
                ('match_status', models.CharField(choices=[('MATCH', 'Watchlist Match Flagged'), ('CLEARED', 'Normal / Non-Watchlist'), ('FLAGGED', 'Suspicious / OCR Unverified')], default='CLEARED', max_length=20)),
                ('watchlist_risk', models.CharField(default='NORMAL', max_length=20)),
                ('speed_estimate', models.CharField(default='42 km/h', max_length=50)),
                ('direction', models.CharField(default='Inbound (Gate 1 -> Zone B)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anpr_detections', to='cameras.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
